### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactor

### ISSUE THREAD

**Issue by aistomin** [aistomin/deutsch-trainer#234]
```
chriss-MacBook-Pro:target andrej$ java -jar deutsch-trainer-1.0-SNAPSHOT.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.aistomin.trainer.deutsch.ui.Trainer.main(Trainer.java:58)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

**Comment by aistomin** [comment]
Done.
